export const GET_ACTIVITY = 'GET_ACTIVITY';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_ERROR = 'GET_ACTIVITY_ERROR';

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS"
export const ADD_TO_FAVORITES_ERROR = "ADD_TO_FAVORITES_ERROR"
export const DELETE_FROM_FAVORITES = "DELETE_FROM_FAVORITES";
export const FETCH_FAVORITES_FROM_FIREBASE = "FETCH_FAVORITES_FROM_FIREBASE";
export const FETCH_FAVORITES_FROM_FIREBASE_SUCCESS = "FETCH_FAVORITES_FROM_FIREBASE_SUCCESS"
export const DELETE_FROM_FAVORITES_ERROR = "DELETE_FROM_FAVORITES_ERROR"

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const GET_COMMENT = "GET_COMMENT";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";

export const ADD_RATING = "ADD_RATING";
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS";
export const ADD_RATING_ERROR = "ADD_RATING_ERROR";

export const GET_RATING = "GET_RATING";
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";
export const GET_RATING_ERROR = "GET_RATING_ERROR";

export const GET_USER_RATING = "GET_USER_RATING";
export const GET_USER_RATING_SUCCESS = "GET_USER_RATING_SUCCESS";
export const GET_USER_RATING_ERROR = "GET_USER_RATING_ERROR";
